version: "3.2"

services:
    mdw:
        image: centos-ssh
        container_name: gpdb-mdw
        tty: true
        restart: always
        ports:
            - "5500:5432"

    sdw1:
        image: centos-ssh
        container_name: gpdb-sdw1
        tty: true
        restart: always

    sdw2:
        image: centos-ssh
        container_name: gpdb-sdw2
        tty: true
        restart: always
