version: '2'  
services:  
  db:
    image: mysql
    container_name: mysql_3308
    environment:
        MYSQL_DATABASE: db_thinkman
        MYSQL_ROOT_PASSWORD: Ab123145
    ports:
      - "3308:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;' --innodb-flush-log-at-trx-commit=0
    restart: always
