version: '2'  

networks:
  think_network:
    external: true

services:  
  mysql:
    image: mysql
    container_name: mysql
    volumes:
        - ./localtime:/etc/localtime:ro
        - ./timezone:/etc/timezone:ro
    environment:
        MYSQL_DATABASE: db_thinkman
        MYSQL_ROOT_PASSWORD: Ab123145
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;' --innodb-flush-log-at-trx-commit=0
    networks:
      - think_network
    restart: always
  
  redis:
    image: redis
    container_name: redis
    volumes:
        - ./localtime:/etc/localtime:ro
        - ./timezone:/etc/timezone:ro
    ports:
      - "6379:6379"
    command: redis-server --requirepass Ab123145
    networks:
      - think_network
    restart: always
