version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    volumes:
      - ./localtime:/etc/localtime:ro
      - ./timezone:/etc/timezone:ro
    ports:
      - "2181:2181"
    restart: always

  kafkai1:
    image: wurstmeister/kafka
    volumes:
      - ./localtime:/etc/localtime:ro
      - ./timezone:/etc/timezone:ro
    ports:
      - "9092:9092"
    environment:
      #KAFKA_ADVERTISED_HOST_NAME: 192.168.1.149
      #KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS: "think-topic:6:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://thinkman-wang.uicp.io:18686
    depends_on:
      - zookeeper
    container_name: kafka1
    restart: always

  kafkai2:
    image: wurstmeister/kafka
    volumes:
      - ./localtime:/etc/localtime:ro
      - ./timezone:/etc/timezone:ro
    ports:
      - "9093:9092"
    environment:
      #KAFKA_ADVERTISED_HOST_NAME: 192.168.1.149
      #KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://thinkman-wang.uicp.io:36278
    depends_on:
      - kafkai1
    container_name: kafka2
    restart: always

  kafkai3:
    image: wurstmeister/kafka
    volumes:
      - ./localtime:/etc/localtime:ro
      - ./timezone:/etc/timezone:ro
    ports:
      - "9094:9092"
    environment:
      #KAFKA_ADVERTISED_HOST_NAME: 192.168.1.149
      #KAFKA_ADVERTISED_PORT: 9094
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://thinkman-wang.uicp.io:18840
    depends_on:
      - kafkai2
    container_name: kafka3
    restart: always
